### ISSUE TITLE
Draw tests failing locally

### ISSUE THREAD

**Issue by caleybrock** [juliandescottes/piskel#533]
I run `grunt test` and the smoke test passes.

I run `grunt test-local` and get 4 failures.
<img width="629" alt="screen shot 2016-08-30 at 1 44 15 pm" src="https://cloud.githubusercontent.com/assets/4640747/18106292/f6bfe208-6eb7-11e6-9e84-757432ef76cd.png">
- `drawing/tests/swapcolor.alllayers.allframes.twice.undo.once.json`
- `drawing/tests/transform.clone.twice.undo.once.json`
- `drawing/tests/move-alllayers-allframes.json`
- and finally, the smoke test also fails (this seems to be a timeout issue). We added a timeout in our fork tests to get the smoke test passing locally: https://github.com/code-dot-org/piskel/blob/master/test/casperjs/SmokeTest.js#L4

I also tried a git bisect and went back a few versions and am seeing the same thing. I'm running OSX and have the following versions (@islemaster is onUbuntu and can get everything but the smoke test to pass).

```
$ PATH=`npm bin`:$PATH casperjs --version
1.0.2
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/caleybrock/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.
$ `npm bin`/phantomjs --version
1.9.8
$ nvm use stable
Now using node v6.4.0 (npm v3.10.3)
$ node --version
v6.4.0
$ npm --version
3.10.3
```

Any ideas on getting these tests passing?

context: I'm working at Code.org (https://github.com/code-dot-org/piskel) and looking to update our fork, but would like to only do this when tests pass.

**Comment by juliandescottes** [comment]
Thanks for opening this issue!

Not sure what I was thinking when I added those tests, but basically they expect that toDataURL() will output the same result on all browsers, and all OS.

Of course this is not what happens in real life and the tests only really work on Chrome + Windows.
I will update the tests to compare the image contents rather than the image data strings.

**Comment by caleybrock** [comment]
That would be awesome, thanks for the quick response!

**Comment by juliandescottes** [comment]
Should be fixed by https://github.com/juliandescottes/piskel/commit/b5fc0f544fbc441bb6a031f94cd9f7c4aa8095d7

Looks like drawing tests are even passing on travis now with this (https://travis-ci.org/juliandescottes/piskel/builds/156373779). So that should also fix @islemaster issues on linux.

**Comment by juliandescottes** [comment]
There was one last issue on OSX only when replaying keyboard events. The last commit on the fix-drawing-tests branch should fix this (https://github.com/juliandescottes/piskel/tree/fix-drawing-tests)

**Comment by caleybrock** [comment]
drawing tests are all passing on your branch - thank you for the quick fix!

**Comment by islemaster** [comment]
FYI, at the head of `fix-drawing-tests` (73b71cf) when I run `grunt test-local` all of the drawing tests pass for me locally, but the smoke test still fails.  Hard-coding the smoke test to use a 10-second delay instead of the 50ms delay use when running `test-local` makes it pass.  Possible that test should have a hard-coded delay?

My environment:

Ubuntu 16.04 LTS 64-bit
Intel Core i7-4770HQ @ 2.20GHz x 8 / 15.6 GiB Memory

```
╰○ node --version
v6.2.2
                                                                                                         
╰○ npm --version
3.9.5
                                                                                                         
╰○ grunt --version
grunt-cli v0.1.13
grunt v0.4.5
                                                                                                         
╰○ `npm bin`/phantomjs --version
1.9.8
# My global phantomjs is >=2.0.0
                                                                                                         
╰○ PATH=`npm bin`:$PATH casperjs --version
1.0.2
# Adjusting PATH forces casperjs to use phantomjs 1.9.3
```

**Comment by islemaster** [comment]
Also, thanks for taking a look at this! :+1: :raised_hands: :tada:

**Comment by juliandescottes** [comment]
> FYI, at the head of fix-drawing-tests (73b71cf) when I run grunt test-local all of the drawing tests pass for me locally, but the smoke test still fails. Hard-coding the smoke test to use a 10-second delay instead of the 50ms delay use when running test-local makes it pass.

We should totally increase the delay. As you can see in the gruntfile we use 10 seconds for travis already and 50ms when running locally. Let's use 10 seconds everywhere. I guess that when it was the only test I had, I wanted it to fail as quickly as possible, but doesn't make much sense anymore.

**Comment by islemaster** [comment]
FWIW, the 50ms timeout is not a problem in the drawing tests for me, only the smoke test.  Probably don't need to run the drawing tests 200x slower just because the smoke test is giving me trouble!

**Comment by juliandescottes** [comment]
Sure, I was talking about the smoke test delay as well (the one defined in Gruntfile.js)
Don't intend to change the 50ms step in the DrawingTests :) (this on is defined in DrawingTestPlayer.js)

**Comment by juliandescottes** [comment]
... OK I didn't remember the delay was also applied to the DrawingTests, your comment makes much more sense now :/ 

I don't actually think the delay is needed for the DrawingTest. And I also will change the behavior of the smoke test so that instead of waiting, we just timeout and fail after 10 seconds.

**Comment by juliandescottes** [comment]
Merged the branch with master. 

@caleybrock Can you test and close this issue if everything's ok?

**Comment by caleybrock** [comment]
Yep, testing right now.

**Comment by caleybrock** [comment]
Works for me, thanks so much!
